#!/usr/bin/env bash

THIS_DIR="$(realpath "$(dirname "${BASH_SOURCE[0]}")")"
cd "${THIS_DIR}/.." || exit $?

# find each .sql file in migrations dir and run it against the filmswap.db file

for file in migrations/*.sql; do
	echo "Running $file"
	sqlite3 filmswap.db < "$file" || true
done
