#!/usr/bin/env bash

set -e

BASE_DIR="$(realpath "$(dirname "${BASH_SOURCE[0]}")"/..)"
cd "${BASE_DIR}" || exit $?

if [[ ! -e '.venv' ]]; then
	echo 'No virtual environment found. Run ./scripts/create-venv first' >&2
	exit 1
fi

exec .venv/bin/python -m filmswap run
